[package]
name = "idsmith-python"
version = "0.5.2"
edition = "2021"
publish = false

[lib]
name = "_idsmith"
crate-type = ["cdylib"]

[dependencies]
idsmith = { path = "../..", default-features = false }
rand = "0.8"
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py38"] }
